DROP TABLE IF EXISTS BC_ACL_HISTORY;
DROP TABLE IF EXISTS BC_ACL_CONTROL;
DROP TABLE IF EXISTS BC_ACL_WAY;

-- 访问方式
CREATE TABLE BC_ACL_WAY(
	ID INT NOT NULL,
	DOC_TYPE varchar(255) NOT NULL,
	DOC_ID INT NOT NULL,
	WAY INT NOT NULL,
	CONSTRAINT BCPK_ACL_WAY PRIMARY KEY (ID),
	CONSTRAINT BCUK_ACL_WAY_DOC UNIQUE (DOC_TYPE, DOC_ID, WAY)
);
COMMENT ON TABLE BC_ACL_WAY IS '访问方式';
COMMENT ON COLUMN BC_ACL_WAY.ID IS 'ID';
COMMENT ON COLUMN BC_ACL_WAY.DOC_ID IS '文档标识';
COMMENT ON COLUMN BC_ACL_WAY.DOC_TYPE IS '文档类型';
COMMENT ON COLUMN BC_ACL_WAY.WAY IS '访问方式 : 1-查阅,2-编辑';

-- 访问控制
CREATE TABLE BC_ACL_CONTROL(
	ID INT NOT NULL,
	WAY_ID INT NOT NULL,
	ACTOR_ID INT NOT NULL,
	ORDER_ INT DEFAULT 0 NOT NULL,
	AUTHOR_ID INT NOT NULL,
	FILE_DATE TIMESTAMP NOT NULL,
	MODIFIER_ID INT,
	MODIFIED_DATE TIMESTAMP,
	CONSTRAINT BCPK_ACL_CONTROL PRIMARY KEY (ID)
);
COMMENT ON TABLE BC_ACL_CONTROL IS '访问控制';
COMMENT ON COLUMN BC_ACL_CONTROL.ID IS 'ID';
COMMENT ON COLUMN BC_ACL_CONTROL.WAY_ID IS '访问方式ID';
COMMENT ON COLUMN BC_ACL_CONTROL.ACTOR_ID IS '访问者ID: 对应Actor的ID';
COMMENT ON COLUMN BC_ACL_CONTROL.ORDER_ IS '排序号: 针对同一文档同一访问类型的不同访问者之间的排序';
COMMENT ON COLUMN BC_ACL_CONTROL.AUTHOR_ID IS '创建人ID';
COMMENT ON COLUMN BC_ACL_CONTROL.FILE_DATE IS '创建时间';
COMMENT ON COLUMN BC_ACL_CONTROL.MODIFIER_ID IS '最后修改人ID';
COMMENT ON COLUMN BC_ACL_CONTROL.MODIFIED_DATE IS '最后修改时间';
ALTER TABLE BC_ACL_CONTROL ADD CONSTRAINT BCFK_ACL_CONTROL_WAY FOREIGN KEY (WAY_ID)
	REFERENCES BC_ACL_WAY (ID) ON UPDATE RESTRICT ON DELETE CASCADE;
ALTER TABLE BC_ACL_CONTROL ADD CONSTRAINT BCFK_ACL_CONTROL_ACTOR FOREIGN KEY (ACTOR_ID)
	REFERENCES BC_IDENTITY_ACTOR (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE BC_ACL_CONTROL ADD CONSTRAINT BCFK_ACL_CONTROL_AUTHOR FOREIGN KEY (AUTHOR_ID)
	REFERENCES BC_IDENTITY_ACTOR (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE BC_ACL_CONTROL ADD CONSTRAINT BCFK_ACL_CONTROL_MODIFIER FOREIGN KEY (MODIFIER_ID)
	REFERENCES BC_IDENTITY_ACTOR (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- 访问历史
CREATE TABLE BC_ACL_HISTORY(
	ID INT NOT NULL,
	WAY_ID INT NOT NULL,
	ACTOR_HID INT NOT NULL,
	ACCESS_DATE TIMESTAMP NOT NULL,
	CONSTRAINT BCPK_ACL_HISTORY PRIMARY KEY (ID)
);
COMMENT ON TABLE BC_ACL_HISTORY IS '访问历史';
COMMENT ON COLUMN BC_ACL_HISTORY.ID IS 'ID';
COMMENT ON COLUMN BC_ACL_HISTORY.WAY_ID IS '访问方式ID';
COMMENT ON COLUMN BC_ACL_HISTORY.ACTOR_HID IS '访问者历史ID';
COMMENT ON COLUMN BC_ACL_HISTORY.ACCESS_DATE IS '访问时间';
ALTER TABLE BC_ACL_HISTORY ADD CONSTRAINT BCFK_ACL_HISTORY_WAY FOREIGN KEY (WAY_ID)
	REFERENCES BC_ACL_WAY (ID) ON UPDATE RESTRICT ON DELETE CASCADE;
ALTER TABLE BC_ACL_HISTORY ADD CONSTRAINT BCFK_ACL_HISTORY_ACTOR FOREIGN KEY (ACTOR_HID)
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
