DROP TABLE IF EXISTS BC_ACL_HISTORY;
DROP TABLE IF EXISTS BC_ACL_ACTOR;
DROP TABLE IF EXISTS BC_ACL_DOC;

-- 访问对象
CREATE TABLE BC_ACL_DOC(
	ID INT NOT NULL,
	DOC_ID VARCHAR(255) NOT NULL,
	DOC_TYPE VARCHAR(255) NOT NULL,
	DOC_NAME VARCHAR(255) NOT NULL,
	AUTHOR_ID INT NOT NULL,
	FILE_DATE TIMESTAMP NOT NULL,
	MODIFIER_ID INT,
	MODIFIED_DATE TIMESTAMP,
	CONSTRAINT BCPK_ACL_DOC PRIMARY KEY (ID),
	CONSTRAINT BCUK_ACL_DOC UNIQUE (DOC_ID, DOC_TYPE)
);
COMMENT ON TABLE BC_ACL_DOC IS '访问对象';
COMMENT ON COLUMN BC_ACL_DOC.ID IS 'ID';
COMMENT ON COLUMN BC_ACL_DOC.DOC_ID IS '文档标识';
COMMENT ON COLUMN BC_ACL_DOC.DOC_TYPE IS '文档类型';
COMMENT ON COLUMN BC_ACL_DOC.DOC_NAME IS '文档名称';
COMMENT ON COLUMN BC_ACL_DOC.AUTHOR_ID IS '创建人ID';
COMMENT ON COLUMN BC_ACL_DOC.FILE_DATE IS '创建时间';
COMMENT ON COLUMN BC_ACL_DOC.MODIFIER_ID IS '最后修改人ID';
COMMENT ON COLUMN BC_ACL_DOC.MODIFIED_DATE IS '最后修改时间';
ALTER TABLE BC_ACL_DOC
	ADD CONSTRAINT BCFK_ACL_DOC_AUTHOR FOREIGN KEY (AUTHOR_ID)
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID)
	ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE BC_ACL_DOC
	ADD CONSTRAINT BCFK_ACL_DOC_MODIFIER FOREIGN KEY (MODIFIER_ID)
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

-- 访问者
CREATE TABLE BC_ACL_ACTOR(
	PID INT DEFAULT 0 NOT NULL,
	AID INT NOT NULL,
	ROLE VARCHAR(255) NOT NULL,
	ORDER_ INT DEFAULT 0 NOT NULL,
	CONSTRAINT BCPK_ACL_ACTOR PRIMARY KEY (PID, AID)
);
COMMENT ON TABLE BC_ACL_ACTOR IS '访问者';
COMMENT ON COLUMN BC_ACL_ACTOR.PID IS '访问对象ID';
COMMENT ON COLUMN BC_ACL_ACTOR.AID IS '访问者ID : 对应Actor的ID';
COMMENT ON COLUMN BC_ACL_ACTOR.ROLE IS '访问权限  : [0]-查阅,[1]-编辑,...';
COMMENT ON COLUMN BC_ACL_ACTOR.ORDER_ IS '排序号';
ALTER TABLE BC_ACL_ACTOR
	ADD CONSTRAINT BCFK_ACL_ACTOR_PID FOREIGN KEY (PID)
	REFERENCES BC_ACL_DOC (ID)
	ON UPDATE RESTRICT ON DELETE CASCADE;
ALTER TABLE BC_ACL_ACTOR
	ADD CONSTRAINT BCFK_ACL_ACTOR FOREIGN KEY (AID)
	REFERENCES BC_IDENTITY_ACTOR (ID)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

-- 访问历史
CREATE TABLE BC_ACL_HISTORY(
	ID INT NOT NULL,
	PID INT NOT NULL,
	AHID INT NOT NULL,
	ROLE VARCHAR(255) NOT NULL,
	ACCESS_DATE TIMESTAMP NOT NULL,
	CONSTRAINT BCPK_ACL_HISTORY PRIMARY KEY (ID)
);
COMMENT ON TABLE BC_ACL_HISTORY IS '访问历史';
COMMENT ON COLUMN BC_ACL_HISTORY.ID IS 'ID';
COMMENT ON COLUMN BC_ACL_HISTORY.PID IS '访问对象ID';
COMMENT ON COLUMN BC_ACL_HISTORY.AHID IS '访问者历史ID';
COMMENT ON COLUMN BC_ACL_HISTORY.ROLE IS '访问权限  : [0]-查阅,[1]-编辑,...';
COMMENT ON COLUMN BC_ACL_HISTORY.ACCESS_DATE IS '访问时间';
ALTER TABLE BC_ACL_HISTORY
	ADD CONSTRAINT BCFK_ACL_HISTORY_PID FOREIGN KEY (PID)
	REFERENCES BC_ACL_DOC (ID)
	ON UPDATE RESTRICT ON DELETE CASCADE;
ALTER TABLE BC_ACL_HISTORY
	ADD CONSTRAINT BCFK_ACL_HISTORY_ACTORHISTORY FOREIGN KEY (AHID)
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID)
	ON UPDATE RESTRICT ON DELETE RESTRICT;