DROP TABLE IF EXISTS BC_EMAIL_HISTORY;
DROP TABLE IF EXISTS BC_EMAIL_TO;
DROP TABLE IF EXISTS BC_EMAIL_TRASH;
DROP TABLE IF EXISTS BC_EMAIL;

CREATE TABLE BC_EMAIL(
	ID INT NOT NULL,
	UID_ VARCHAR(32) NOT NULL,
	TYPE_ INT DEFAULT 0 NOT NULL,
	PID INT,
	STATUS_ INT DEFAULT 0 NOT NULL,
	SUBJECT VARCHAR(500) NOT NULL,
	CONTENT TEXT,
	SEND_DATE TIMESTAMP,
	SENDER_ID INT NOT NULL,
	FILE_DATE TIMESTAMP NOT NULL,
	CONSTRAINT BCPK_EMAIL PRIMARY KEY (ID)
);
COMMENT ON TABLE BC_EMAIL IS '邮件发件箱';
COMMENT ON COLUMN BC_EMAIL.ID IS 'ID';
COMMENT ON COLUMN BC_EMAIL.UID_ IS 'UID';
COMMENT ON COLUMN BC_EMAIL.TYPE_ IS '类型 : 0-新邮件,1-回复,2-转发';
COMMENT ON COLUMN BC_EMAIL.PID IS '源邮件ID : 转发回复时使用';
COMMENT ON COLUMN BC_EMAIL.STATUS_ IS '状态 : 0-草稿,1-已发送';
COMMENT ON COLUMN BC_EMAIL.SUBJECT IS '标题';
COMMENT ON COLUMN BC_EMAIL.CONTENT IS '内容';
COMMENT ON COLUMN BC_EMAIL.SEND_DATE IS '发送日期 : 对于提醒信息与创建时间相等';
COMMENT ON COLUMN BC_EMAIL.SENDER_ID IS '发送人ID : 对应Actor的ID';
COMMENT ON COLUMN BC_EMAIL.FILE_DATE IS '创建时间';
ALTER TABLE BC_EMAIL ADD CONSTRAINT BCFK_EMAIL_PID FOREIGN KEY (PID)
	REFERENCES BC_EMAIL (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE BC_EMAIL ADD CONSTRAINT BCFK_EMAIL_SENDER FOREIGN KEY (SENDER_ID)
	REFERENCES BC_IDENTITY_ACTOR (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

CREATE TABLE BC_EMAIL_TO(
	ID INT NOT NULL,
	PID INT DEFAULT 0 NOT NULL,
	TYPE_ INT NOT NULL,
	RECEIVER_ID INT NOT NULL,
	ORDER_ INT DEFAULT 0 NOT NULL,
	READ_ BOOLEAN DEFAULT 'false' NOT NULL,
	CONSTRAINT BCPK_EMAIL_TO PRIMARY KEY (ID)
);
COMMENT ON TABLE BC_EMAIL_TO IS '邮件收件箱';
COMMENT ON COLUMN BC_EMAIL_TO.ID IS 'ID';
COMMENT ON COLUMN BC_EMAIL_TO.PID IS '邮件ID';
COMMENT ON COLUMN BC_EMAIL_TO.TYPE_ IS '发送类型 : 0-主送,1-抄送,2-密送';
COMMENT ON COLUMN BC_EMAIL_TO.RECEIVER_ID IS '收件人ID : 对应Actor的ID';
COMMENT ON COLUMN BC_EMAIL_TO.ORDER_ IS '排序号 : 针对同一发送类型的不同收件人之间的排序';
COMMENT ON COLUMN BC_EMAIL_TO.READ_ IS '已阅标记';
ALTER TABLE BC_EMAIL_TO ADD CONSTRAINT BCFK_EMAIL_TO_PID FOREIGN KEY (PID)
	REFERENCES BC_EMAIL (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE BC_EMAIL_TO ADD CONSTRAINT BCFK_EMAIL_TO_RECEIVER FOREIGN KEY (RECEIVER_ID)
	REFERENCES BC_IDENTITY_ACTOR (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

CREATE TABLE BC_EMAIL_HISTORY(
	ID INT NOT NULL,
	PID INT NOT NULL,
	READER_ID INT NOT NULL,
	FILE_DATE TIMESTAMP NOT NULL,
	CONSTRAINT BCPK_EMAIL_HISTORY PRIMARY KEY (ID)
);
COMMENT ON TABLE BC_EMAIL_HISTORY IS '邮件查阅历史';
COMMENT ON COLUMN BC_EMAIL_HISTORY.ID IS 'ID';
COMMENT ON COLUMN BC_EMAIL_HISTORY.PID IS '邮件ID';
COMMENT ON COLUMN BC_EMAIL_HISTORY.READER_ID IS '查阅人ID : 对应Actor的ID';
COMMENT ON COLUMN BC_EMAIL_HISTORY.FILE_DATE IS '查阅时间';
ALTER TABLE BC_EMAIL_HISTORY ADD CONSTRAINT BCFK_EMAIL_HISTORY_PID FOREIGN KEY (PID)
	REFERENCES BC_EMAIL (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE BC_EMAIL_HISTORY ADD CONSTRAINT BCFK_EMAIL_HISTORY_READER FOREIGN KEY (READER_ID)
	REFERENCES BC_IDENTITY_ACTOR (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

CREATE TABLE BC_EMAIL_TRASH(
	ID INT NOT NULL,
	PID INT NOT NULL,
	OWNER_ID INT NOT NULL,
	STATUS_ INT DEFAULT 0 NOT NULL,
	HANDLE_DATE TIMESTAMP NOT NULL,
	CONSTRAINT BCPK_EMAIL_TRASH PRIMARY KEY (ID)
);
COMMENT ON TABLE BC_EMAIL_TRASH IS '邮件垃圾箱';
COMMENT ON COLUMN BC_EMAIL_TRASH.ID IS 'ID';
COMMENT ON COLUMN BC_EMAIL_TRASH.PID IS '邮件ID';
COMMENT ON COLUMN BC_EMAIL_TRASH.OWNER_ID IS '所有者ID : 对应Actor的ID';
COMMENT ON COLUMN BC_EMAIL_TRASH.STATUS_ IS '状态 : 0-可恢复,1-已删除';
COMMENT ON COLUMN BC_EMAIL_TRASH.HANDLE_DATE IS '操作时间';
ALTER TABLE BC_EMAIL_TRASH ADD CONSTRAINT BCFK_EMAIL_TRASH_PID FOREIGN KEY (PID)
	REFERENCES BC_EMAIL (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE BC_EMAIL_TRASH ADD CONSTRAINT BCFK_EMAIL_TRASH_OWNER FOREIGN KEY (OWNER_ID)
	REFERENCES BC_IDENTITY_ACTOR (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;