DROP TABLE IF EXISTS BC_IDCARD_CHECK;
DROP TABLE IF EXISTS BC_IDCARD;

CREATE TABLE BC_IDCARD(
	ID INT NOT NULL,
	CODE VARCHAR(20) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	SEX VARCHAR(10) NOT NULL,
	FOLK VARCHAR(10) NOT NULL,
	BIRTHDATE TIMESTAMP NOT NULL,
	ISSUE VARCHAR(255) NOT NULL,
	START_DATE TIMESTAMP NOT NULL,
	END_DATE TIMESTAMP NOT NULL,
	ADDRESS VARCHAR(500) NOT NULL,
	NEW_ADDRESS VARCHAR(500),
	PIC BYTEA,
	CONSTRAINT BCPK_IDCARD PRIMARY KEY (ID),
	CONSTRAINT BCUK_IDCARD_NUM UNIQUE (CODE)
);
COMMENT ON TABLE BC_IDCARD IS '身份证';
COMMENT ON COLUMN BC_IDCARD.ID IS 'ID';
COMMENT ON COLUMN BC_IDCARD.CODE IS '身份证号';
COMMENT ON COLUMN BC_IDCARD.NAME IS '姓名';
COMMENT ON COLUMN BC_IDCARD.SEX IS '性别';
COMMENT ON COLUMN BC_IDCARD.FOLK IS '民族 : (不带路径的部分)';
COMMENT ON COLUMN BC_IDCARD.BIRTHDATE IS '出生日期';
COMMENT ON COLUMN BC_IDCARD.ISSUE IS '签发机关';
COMMENT ON COLUMN BC_IDCARD.START_DATE IS '有效期-开始';
COMMENT ON COLUMN BC_IDCARD.END_DATE IS '有效期-结束';
COMMENT ON COLUMN BC_IDCARD.ADDRESS IS '住址';
COMMENT ON COLUMN BC_IDCARD.NEW_ADDRESS IS '最新住址';
COMMENT ON COLUMN BC_IDCARD.PIC IS '图像';

CREATE TABLE BC_IDCARD_CHECK(
	ID INT NOT NULL,
	PID INT NOT NULL,
	CHECK_DATE TIMESTAMP NOT NULL,
	CONSTRAINT BCPK_IDCARD_CHECK PRIMARY KEY (ID)
);
COMMENT ON TABLE BC_IDCARD_CHECK IS '刷卡记录';
COMMENT ON COLUMN BC_IDCARD_CHECK.ID IS 'ID';
COMMENT ON COLUMN BC_IDCARD_CHECK.PID IS '身份证';
COMMENT ON COLUMN BC_IDCARD_CHECK.CHECK_DATE IS '验证时间';
ALTER TABLE BC_IDCARD_CHECK ADD CONSTRAINT BC_IDCARD_CHECK_PID FOREIGN KEY (PID)
	REFERENCES BC_IDCARD (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- test
INSERT INTO bc_idcard(id, code, name, sex, folk, birthdate, issue, start_date, end_date, address)
    VALUES (1, '440721197602067338','dragon', '男', '汉', '1976-02-06', '广州市公安局海珠分局', '2006-05-18', '2026-05-18', 'address');
INSERT INTO bc_idcard_check(id, pid, check_date)
    VALUES (1, 1, '2012-11-30 00:00:00');
