DROP TABLE IF EXISTS BC_ATD_RECORD;

-- 考勤记录
CREATE TABLE BC_ATD_RECORD(
	ID INT NOT NULL,
	TYPE_ INT NOT NULL,
	DID INT,
	AID INT NOT NULL,
	DATE_ DATE NOT NULL,
	TIME_ TIME NOT NULL,
	DESC_ VARCHAR(255) NOT NULL,
	AUTHOR_ID INT,
	FILE_DATE TIMESTAMP NOT NULL,
	MODIFIER_ID INT,
	MODIFIED_DATE TIMESTAMP,
	CONSTRAINT BCPK_ATD_RECORD PRIMARY KEY (ID)
);
COMMENT ON TABLE BC_ATD_RECORD IS '考勤记录';
COMMENT ON COLUMN BC_ATD_RECORD.ID IS 'ID';
COMMENT ON COLUMN BC_ATD_RECORD.TYPE_ IS '考勤类型 : 0-上班,1-下班';
COMMENT ON COLUMN BC_ATD_RECORD.DID IS '考勤设备 : 系统手动创建的记录为null';
COMMENT ON COLUMN BC_ATD_RECORD.AID IS '考勤用户';
COMMENT ON COLUMN BC_ATD_RECORD.DATE_ IS '考勤日期';
COMMENT ON COLUMN BC_ATD_RECORD.TIME_ IS '考勤时间';
COMMENT ON COLUMN BC_ATD_RECORD.DESC_ IS '备注 : 设备名称或补登记说明';
COMMENT ON COLUMN BC_ATD_RECORD.AUTHOR_ID IS '创建人 : 通过设备登记时为null';
COMMENT ON COLUMN BC_ATD_RECORD.FILE_DATE IS '创建时间';
COMMENT ON COLUMN BC_ATD_RECORD.MODIFIER_ID IS '最后修改人';
COMMENT ON COLUMN BC_ATD_RECORD.MODIFIED_DATE IS '最后修改时间';
ALTER TABLE BC_ATD_RECORD
	ADD CONSTRAINT BCFK_ATD_RECORD_DID FOREIGN KEY (DID)
	REFERENCES BC_DEVICE (ID)
	ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE BC_ATD_RECORD
	ADD CONSTRAINT BCFK_ATD_RECORD_AUTHOR FOREIGN KEY (AUTHOR_ID)
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID)
	ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE BC_ATD_RECORD
	ADD CONSTRAINT BCFK_ATD_RECORD_MODIFIER FOREIGN KEY (MODIFIER_ID)
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID)
	ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE BC_ATD_RECORD
	ADD CONSTRAINT BCFK_ATD_RECORD_AID FOREIGN KEY (AID)
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID)
	ON UPDATE RESTRICT ON DELETE RESTRICT;



