
/* Drop Tables */

DROP TABLE IF EXISTS BC_DEVICE_EVENT;
DROP TABLE IF EXISTS BC_DEVICE;
DROP TABLE IF EXISTS BC_IDENTITY_ACTOR_HISTORY;




/* Create Tables */

CREATE TABLE BC_DEVICE
(
	ID INT NOT NULL,
	CODE VARCHAR(255) NOT NULL UNIQUE,
	SN VARCHAR(255) NOT NULL UNIQUE,
	MODEL VARCHAR(255) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	BUY_DATE DATE NOT NULL,
	FILE_DATE TIMESTAMP NOT NULL,
	AUTHOR_ID INT NOT NULL,
	MODIFIER_ID INT NOT NULL,
	MODIFIED_DATE TIMESTAMP NOT NULL,
	DESC_ VARCHAR(4000),
	CONSTRAINT BCPK_DEVICE PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE BC_DEVICE_EVENT
(
	ID INT NOT NULL,
	DEVICE_ID INT NOT NULL,
	TYPE_ VARCHAR(255) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	FILE_DATE TIMESTAMP NOT NULL,
	AUTHOR_ID INT NOT NULL,
	CONSTRAINT BCPK_DEVICE_EVENT PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE BC_IDENTITY_ACTOR_HISTORY
(
	ID INT NOT NULL,
	CONSTRAINT BCPK_IDENTITY_ACTOR_HISTORY PRIMARY KEY (ID)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE BC_DEVICE_EVENT
	ADD CONSTRAINT BCFK_DEVICE_EVENT_DID FOREIGN KEY (DEVICE_ID)
	REFERENCES BC_DEVICE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BC_DEVICE
	ADD CONSTRAINT BCFK_DEVICE_AUTHOR FOREIGN KEY (AUTHOR_ID)
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BC_DEVICE
	ADD CONSTRAINT BCFK_DEVICE_MODIFIER FOREIGN KEY (MODIFIER_ID)
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BC_DEVICE_EVENT
	ADD CONSTRAINT BCFK_DEVICE_EVENT_AUTHOR FOREIGN KEY (AUTHOR_ID)
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



/* Comments */

COMMENT ON TABLE BC_DEVICE IS '设备';
COMMENT ON COLUMN BC_DEVICE.ID IS 'ID';
COMMENT ON COLUMN BC_DEVICE.CODE IS '编码';
COMMENT ON COLUMN BC_DEVICE.SN IS '序列号';
COMMENT ON COLUMN BC_DEVICE.MODEL IS '型号';
COMMENT ON COLUMN BC_DEVICE.NAME IS '名称';
COMMENT ON COLUMN BC_DEVICE.BUY_DATE IS '购买日期';
COMMENT ON COLUMN BC_DEVICE.FILE_DATE IS '创建时间';
COMMENT ON COLUMN BC_DEVICE.AUTHOR_ID IS '创建人ID';
COMMENT ON COLUMN BC_DEVICE.MODIFIER_ID IS '最后修改人';
COMMENT ON COLUMN BC_DEVICE.MODIFIED_DATE IS '最后修改时间';
COMMENT ON COLUMN BC_DEVICE.DESC_ IS '备注';
COMMENT ON TABLE BC_DEVICE_EVENT IS '设备事件';
COMMENT ON COLUMN BC_DEVICE_EVENT.ID IS 'ID';
COMMENT ON COLUMN BC_DEVICE_EVENT.DEVICE_ID IS '设备ID';
COMMENT ON COLUMN BC_DEVICE_EVENT.TYPE_ IS '事件类型';
COMMENT ON COLUMN BC_DEVICE_EVENT.NAME IS '姓名';
COMMENT ON COLUMN BC_DEVICE_EVENT.FILE_DATE IS '创建时间';
COMMENT ON COLUMN BC_DEVICE_EVENT.AUTHOR_ID IS '创建人ID';
COMMENT ON TABLE BC_IDENTITY_ACTOR_HISTORY IS '参与者历史';
COMMENT ON COLUMN BC_IDENTITY_ACTOR_HISTORY.ID IS 'ID';



