-- 工作事项
create table BC_WORK (
    ID int NOT NULL auto_increment,
    UID_ varchar(36) COMMENT '全局标识',
    STATUS_ int(1) NOT NULL default 0 COMMENT '状态',
    INNER_ int(1) NOT NULL default 0 COMMENT '未用',
    
    CLASSIFIER varchar(500) NOT NULL COMMENT '分类词,可多级分类,级间使用/连接,如“发文类/正式发文”',
    SUBJECT varchar(255) NOT NULL COMMENT '标题',
    FROM_ID int COMMENT '来源标识',
    FROM_TYPE int COMMENT '来源类型',
    FROM_INFO varchar(255) COMMENT '来源描述',
    OPEN_URL varchar(255) COMMENT '打开的Url模板',
    CONTENT text COMMENT '内容',
    primary key (ID)
) COMMENT='工作事项';
ALTER TABLE BC_WORK ADD INDEX IDX_WORK_FROMID (FROM_ID);

-- 待办事项
create table BC_WORK_TODO (
    ID int NOT NULL auto_increment,
    UID_ varchar(36) COMMENT '未用',
    STATUS_ int(1) NOT NULL default 0 COMMENT '未用',
    INNER_ int(1) NOT NULL default 0 COMMENT '未用',
    
    WORK_ID int NOT NULL COMMENT '工作事项ID',
    SENDER_ID int NOT NULL COMMENT '发送者',
    SEND_DATE datetime NOT NULL COMMENT '发送时间',
    WORKER_ID int NOT NULL COMMENT '发送者',
    INFO varchar(255) COMMENT '附加说明',
    primary key (ID)
) COMMENT='待办事项';
ALTER TABLE BC_WORK_TODO ADD CONSTRAINT FK_TODOWORK_WORK FOREIGN KEY (WORK_ID) 
	REFERENCES BC_WORK (ID);
ALTER TABLE BC_WORK_TODO ADD CONSTRAINT FK_TODOWORK_SENDER FOREIGN KEY (SENDER_ID) 
	REFERENCES BC_IDENTITY_ACTOR (ID);
ALTER TABLE BC_WORK_TODO ADD CONSTRAINT FK_TODOWORK_WORKER FOREIGN KEY (WORKER_ID) 
	REFERENCES BC_IDENTITY_ACTOR (ID);

-- 已办事项
create table BC_WORK_DONE (
    ID int NOT NULL auto_increment,
    UID_ varchar(36) COMMENT '未用',
    STATUS_ int(1) NOT NULL default 0 COMMENT '未用',
    INNER_ int(1) NOT NULL default 0 COMMENT '未用',
    
    FINISH_DATE datetime NOT NULL COMMENT '完成时间',
    FINISH_YEAR int(4) NOT NULL COMMENT '完成时间的年度',
    FINISH_MONTH int(2) NOT NULL COMMENT '完成时间的月份(1-12)',
    FINISH_DAY int(2) NOT NULL COMMENT '完成时间的日(1-31)',

    WORK_ID int NOT NULL COMMENT '工作事项ID',
    SENDER_ID int NOT NULL COMMENT '发送者',
    SEND_DATE datetime NOT NULL COMMENT '发送时间',
    WORKER_ID int NOT NULL COMMENT '发送者',
    INFO varchar(255) COMMENT '附加说明',
    primary key (ID)
) COMMENT='已办事项';
ALTER TABLE BC_WORK_DONE ADD CONSTRAINT FK_DONEWORK_WORK FOREIGN KEY (WORK_ID) 
	REFERENCES BC_WORK (ID);
ALTER TABLE BC_WORK_DONE ADD CONSTRAINT FK_DONEWORK_SENDER FOREIGN KEY (SENDER_ID) 
	REFERENCES BC_IDENTITY_ACTOR (ID);
ALTER TABLE BC_WORK_DONE ADD CONSTRAINT FK_DONEWORK_WORKER FOREIGN KEY (WORKER_ID) 
	REFERENCES BC_IDENTITY_ACTOR (ID);
ALTER TABLE BC_WORK_DONE ADD INDEX IDX_DONEWORK_FINISHDATE (FINISH_YEAR,FINISH_MONTH,FINISH_DAY);
