-- 系统桌面相关模块
-- 桌面快捷方式
create table BC_DESKTOP_SHORTCUT (
    ID number(19) NOT NULL,
    UID_ varchar(36),
    STATUS_ number(1) NOT NULL,
    INNER_ number(1) NOT NULL,
    ORDER_ varchar(100) NOT NULL,
    STANDALONE number(1) NOT NULL,
    NAME varchar(255),
    URL varchar(255),
    ICONCLASS varchar(255),
    MID number(19),
    AID number(19),
    primary key (ID)
);
ALTER TABLE BC_DESKTOP_SHORTCUT ADD CONSTRAINT FK_SHORTCUT_MODULE FOREIGN KEY (MID) 
	REFERENCES BC_SECURITY_MODULE (ID);
ALTER TABLE BC_DESKTOP_SHORTCUT ADD CONSTRAINT FK_SHORTCUT_ACTOR FOREIGN KEY (AID) 
	REFERENCES BC_IDENTITY_ACTOR (ID);
COMMENT ON TABLE BC_DESKTOP_SHORTCUT IS '桌面快捷方式';
COMMENT ON COLUMN BC_DESKTOP_SHORTCUT.UID_ IS '全局标识';
COMMENT ON COLUMN BC_DESKTOP_SHORTCUT.STATUS_ IS '状态：0-已禁用,1-启用中,2-已删除';
COMMENT ON COLUMN BC_DESKTOP_SHORTCUT.INNER_ IS '是否为内置对象:0-否,1-是';
COMMENT ON COLUMN BC_DESKTOP_SHORTCUT.STANDALONE IS '是否在独立的浏览器窗口中打开';
COMMENT ON COLUMN BC_DESKTOP_SHORTCUT.NAME IS '名称,为空则使用模块的名称';
COMMENT ON COLUMN BC_DESKTOP_SHORTCUT.URL IS '地址,为空则使用模块的地址';
COMMENT ON COLUMN BC_DESKTOP_SHORTCUT.ICONCLASS IS '图标样式';
COMMENT ON COLUMN BC_DESKTOP_SHORTCUT.MID IS '对应的模块ID';
COMMENT ON COLUMN BC_DESKTOP_SHORTCUT.AID IS '所属的参与者(如果为上级参与者,如单位部门,则其下的所有参与者都拥有该快捷方式)';
